package com.monitor.model;
// Generated 23/06/2017 12:40:03 PM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Query;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Campana generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "CAMPANA", schema = "MONITOR")
public class Campana  implements Serializable{

	private CampanaId id;
	private String nombre;
	private Date fechaalta;
	private Date inicia;
	private Date termina;
	private Integer status;
	private CliPro cliPro;

	private Set<Sitio> sitios = new HashSet<Sitio>(0);

	public Campana() {
	}

	public Campana(CampanaId id) {
		this.id = id;
	}

	public Campana(CampanaId id, String nombre, Integer status, Set<Sitio> sitios) {
		this.id = id;
		this.nombre = nombre;
		this.status = status;
		this.sitios = sitios;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cveCampana", column = @Column(name = "CVE_CAMPANA", nullable = false, length = 12)),
			@AttributeOverride(name = "cveClipro", column = @Column(name = "CVE_CLIPRO", nullable = false, length = 10)) })
	public CampanaId getId() {
		return this.id;
	}
	public void setId(CampanaId id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "STATUS", precision = 6, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campana")
	public Set<Sitio> getSitios() {
		return this.sitios;
	}

	public void setSitios(Set<Sitio> sitios) {
		this.sitios = sitios;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHAALTA", length = 7)
	public Date getFechaalta() {
		return this.fechaalta;
	}

	public void setFechaalta(Date fechaalta) {
		this.fechaalta = fechaalta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CVE_CLIPRO", referencedColumnName = "CVE_CLIPRO", nullable = false, insertable = false, updatable = false)
	public CliPro getCliPro() {
		return this.cliPro;
	}

	public void setCliPro(CliPro cliPro) {
		this.cliPro = cliPro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INICIA", length = 7)
	public Date getInicia() {
		return inicia;
	}

	public void setInicia(Date inicia) {
		this.inicia = inicia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TERMINA", length = 7)
	public Date getTermina() {
		return termina;
	}

	public void setTermina(Date termina) {
		this.termina = termina;
	}

}
