package com.monitor.model;
// Generated 23/06/2017 01:20:31 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * CliPro generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "CLI_PRO", schema = "MONITOR")
public class CliPro implements java.io.Serializable {

	private String cveClipro;
	private String nombre;
	private int tipo;
	private String padre;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public CliPro() {
	}

	public CliPro(String cveClipro, int tipo) {
		this.cveClipro = cveClipro;
		this.tipo = tipo;
	}

	public CliPro(String cveClipro, String nombre, int tipo, String padre, Set<Usuario> usuarios) {
		this.cveClipro = cveClipro;
		this.nombre = nombre;
		this.tipo = tipo;
		this.padre = padre;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "CVE_CLIPRO", unique = true, nullable = false, length = 10)
	public String getCveClipro() {
		return this.cveClipro;
	}

	public void setCveClipro(String cveClipro) {
		this.cveClipro = cveClipro;
	}

	@Column(name = "NOMBRE", length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "TIPO", nullable = false, precision = 6, scale = 0)
	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	@Column(name = "PADRE", length = 10)
	public String getPadre() {
		return this.padre;
	}

	public void setPadre(String padre) {
		this.padre = padre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliPro")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
