package com.monitor.model;
// Generated 23/06/2017 12:40:03 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FotoId generated by hbm2java
 */
@Embeddable
public class FotoId implements java.io.Serializable {

	private Date fechaHora;
	private String cveCampana;
	private String cveClipro;
	private String email;
	private String cvePlaza;
	private String cveSitio;

	public FotoId() {
	}

	public FotoId(Date fechaHora, String cveCampana, String cveClipro, String email, String cvePlaza, String cveSitio) {
		this.fechaHora = fechaHora;
		this.cveCampana = cveCampana;
		this.cveClipro = cveClipro;
		this.email = email;
		this.cvePlaza = cvePlaza;
		this.cveSitio = cveSitio;
	}

	@Column(name = "FECHA_HORA", nullable = false, length = 7)
	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	@Column(name = "CVE_CAMPANA", nullable = false, length = 12)
	public String getCveCampana() {
		return this.cveCampana;
	}

	public void setCveCampana(String cveCampana) {
		this.cveCampana = cveCampana;
	}

	@Column(name = "CVE_CLIPRO", nullable = false, length = 10)
	public String getCveClipro() {
		return this.cveClipro;
	}

	public void setCveClipro(String cveClipro) {
		this.cveClipro = cveClipro;
	}

	@Column(name = "EMAIL", nullable = false, length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "CVE_PLAZA", nullable = false, length = 10)
	public String getCvePlaza() {
		return this.cvePlaza;
	}

	public void setCvePlaza(String cvePlaza) {
		this.cvePlaza = cvePlaza;
	}

	@Column(name = "CVE_SITIO", nullable = false, length = 20)
	public String getCveSitio() {
		return this.cveSitio;
	}

	public void setCveSitio(String cveSitio) {
		this.cveSitio = cveSitio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FotoId))
			return false;
		FotoId castOther = (FotoId) other;

		return ((this.getFechaHora() == castOther.getFechaHora()) || (this.getFechaHora() != null
				&& castOther.getFechaHora() != null && this.getFechaHora().equals(castOther.getFechaHora())))
				&& ((this.getCveCampana() == castOther.getCveCampana()) || (this.getCveCampana() != null
						&& castOther.getCveCampana() != null && this.getCveCampana().equals(castOther.getCveCampana())))
				&& ((this.getCveClipro() == castOther.getCveClipro()) || (this.getCveClipro() != null
						&& castOther.getCveClipro() != null && this.getCveClipro().equals(castOther.getCveClipro())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getCvePlaza() == castOther.getCvePlaza()) || (this.getCvePlaza() != null
						&& castOther.getCvePlaza() != null && this.getCvePlaza().equals(castOther.getCvePlaza())))
				&& ((this.getCveSitio() == castOther.getCveSitio()) || (this.getCveSitio() != null
						&& castOther.getCveSitio() != null && this.getCveSitio().equals(castOther.getCveSitio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFechaHora() == null ? 0 : this.getFechaHora().hashCode());
		result = 37 * result + (getCveCampana() == null ? 0 : this.getCveCampana().hashCode());
		result = 37 * result + (getCveClipro() == null ? 0 : this.getCveClipro().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getCvePlaza() == null ? 0 : this.getCvePlaza().hashCode());
		result = 37 * result + (getCveSitio() == null ? 0 : this.getCveSitio().hashCode());
		return result;
	}

}
