package com.monitor.model;
// Generated 27/06/2017 01:30:20 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;

/**
 * Foto generated by hbm2java
 */
@Entity
@Table(name = "FOTO", schema = "MONITOR")
@Cacheable(false)
public class Foto implements java.io.Serializable {

	private FotoId id;
	private Sitio sitio;
	private Usuario usuario;
	private String fotoPath;
	private String comentario;
	private Integer calificacion;
	private Double latitudGps;
	private Double longitudGps;

	public Foto() {
	}

	public Foto(FotoId id, Sitio sitio, Usuario usuario) {
		this.id = id;
		this.sitio = sitio;
		this.usuario = usuario;
	}

	public Foto(FotoId id, Sitio sitio, Usuario usuario, String fotoPath, String comentario, Integer calificacion,
			Double latitudGps, Double longitudGps) {
		this.id = id;
		this.sitio = sitio;
		this.usuario = usuario;
		this.fotoPath = fotoPath;
		this.comentario = comentario;
		this.calificacion = calificacion;
		this.latitudGps = latitudGps;
		this.longitudGps = longitudGps;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fechaHora", column = @Column(name = "FECHA_HORA", nullable = false, length = 7)),
			@AttributeOverride(name = "cveCampana", column = @Column(name = "CVE_CAMPANA", nullable = false, length = 12)),
			@AttributeOverride(name = "cveClipro", column = @Column(name = "CVE_CLIPRO", nullable = false, length = 10)),
			@AttributeOverride(name = "email", column = @Column(name = "EMAIL", nullable = false, length = 20)),
			@AttributeOverride(name = "cvePlaza", column = @Column(name = "CVE_PLAZA", nullable = false, length = 10)),
			@AttributeOverride(name = "cveSitio", column = @Column(name = "CVE_SITIO", nullable = false, length = 20)) })
	public FotoId getId() {
		return this.id;
	}

	public void setId(FotoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CVE_CAMPANA", referencedColumnName = "CVE_CAMPANA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CVE_CLIPRO", referencedColumnName = "CVE_CLIPRO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CVE_PLAZA", referencedColumnName = "CVE_PLAZA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CVE_SITIO", referencedColumnName = "CVE_SITIO", nullable = false, insertable = false, updatable = false) })
	public Sitio getSitio() {
		return this.sitio;
	}

	public void setSitio(Sitio sitio) {
		this.sitio = sitio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMAIL", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "FOTO_PATH", length = 100)
	public String getFotoPath() {
		return this.fotoPath;
	}

	public void setFotoPath(String fotoPath) {
		this.fotoPath = fotoPath;
	}

	@Column(name = "COMENTARIO", length = 100)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "CALIFICACION", precision = 6, scale = 0)
	public Integer getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Integer calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "LATITUD_GPS", precision = 126, scale = 0)
	public Double getLatitudGps() {
		return this.latitudGps;
	}

	public void setLatitudGps(Double latitudGps) {
		this.latitudGps = latitudGps;
	}

	@Column(name = "LONGITUD_GPS", precision = 126, scale = 0)
	public Double getLongitudGps() {
		return this.longitudGps;
	}

	public void setLongitudGps(Double longitudGps) {
		this.longitudGps = longitudGps;
	}

}
