package com.monitor.model;
// Generated 23/06/2017 12:40:03 PM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Query;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Plaza generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "PLAZA", schema = "MONITOR")
public class Plaza implements Serializable{

	private String cvePlaza;
	private String nombre;
	private Integer status;
	private String padre;
	private Integer tipo;
	private String cveClipro;
	private Set<Sitio> sitios = new HashSet<Sitio>(0);

	public Plaza() {
	}

	public Plaza(String cvePlaza) {
		this.cvePlaza = cvePlaza;
	}

	public Plaza(String cvePlaza, String nombre, Integer status, String padre, Integer tipo, String cveClipro,
			Set<Sitio> sitios) {
		this.cvePlaza = cvePlaza;
		this.nombre = nombre;
		this.status = status;
		this.padre = padre;
		this.tipo = tipo;
		this.cveClipro = cveClipro;
		this.sitios = sitios;
	}

	@Id

	@Column(name = "CVE_PLAZA", unique = true, nullable = false, length = 10)
	public String getCvePlaza() {
		return this.cvePlaza;
	}

	public void setCvePlaza(String cvePlaza) {
		this.cvePlaza = cvePlaza;
	}

	@Column(name = "NOMBRE", length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "STATUS", precision = 6, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "PADRE", length = 10)
	public String getPadre() {
		return this.padre;
	}

	public void setPadre(String padre) {
		this.padre = padre;
	}

	@Column(name = "TIPO", precision = 6, scale = 0)
	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	@Column(name = "CVE_CLIPRO", length = 10)
	public String getCveClipro() {
		return this.cveClipro;
	}

	public void setCveClipro(String cveClipro) {
		this.cveClipro = cveClipro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plaza")
	public Set<Sitio> getSitios() {
		return this.sitios;
	}

	public void setSitios(Set<Sitio> sitios) {
		this.sitios = sitios;
	}



}
