package com.monitor.model;
// Generated 23/06/2017 12:40:03 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SitioId generated by hbm2java
 */
@Embeddable
public class SitioId implements java.io.Serializable {

	private String cveCampana;
	private String cveClipro;
	private String cvePlaza;
	private String cveSitio;

	public SitioId() {
	}

	public SitioId(String cveCampana, String cveClipro, String cvePlaza, String cveSitio) {
		this.cveCampana = cveCampana;
		this.cveClipro = cveClipro;
		this.cvePlaza = cvePlaza;
		this.cveSitio = cveSitio;
	}

	@Column(name = "CVE_CAMPANA", nullable = false, length = 12)
	public String getCveCampana() {
		return this.cveCampana;
	}

	public void setCveCampana(String cveCampana) {
		this.cveCampana = cveCampana;
	}

	@Column(name = "CVE_CLIPRO", nullable = false, length = 10)
	public String getCveClipro() {
		return this.cveClipro;
	}

	public void setCveClipro(String cveClipro) {
		this.cveClipro = cveClipro;
	}

	@Column(name = "CVE_PLAZA", nullable = false, length = 10)
	public String getCvePlaza() {
		return this.cvePlaza;
	}

	public void setCvePlaza(String cvePlaza) {
		this.cvePlaza = cvePlaza;
	}

	@Column(name = "CVE_SITIO", nullable = false, length = 20)
	public String getCveSitio() {
		return this.cveSitio;
	}

	public void setCveSitio(String cveSitio) {
		this.cveSitio = cveSitio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SitioId))
			return false;
		SitioId castOther = (SitioId) other;

		return ((this.getCveCampana() == castOther.getCveCampana()) || (this.getCveCampana() != null
				&& castOther.getCveCampana() != null && this.getCveCampana().equals(castOther.getCveCampana())))
				&& ((this.getCveClipro() == castOther.getCveClipro()) || (this.getCveClipro() != null
						&& castOther.getCveClipro() != null && this.getCveClipro().equals(castOther.getCveClipro())))
				&& ((this.getCvePlaza() == castOther.getCvePlaza()) || (this.getCvePlaza() != null
						&& castOther.getCvePlaza() != null && this.getCvePlaza().equals(castOther.getCvePlaza())))
				&& ((this.getCveSitio() == castOther.getCveSitio()) || (this.getCveSitio() != null
						&& castOther.getCveSitio() != null && this.getCveSitio().equals(castOther.getCveSitio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCveCampana() == null ? 0 : this.getCveCampana().hashCode());
		result = 37 * result + (getCveClipro() == null ? 0 : this.getCveClipro().hashCode());
		result = 37 * result + (getCvePlaza() == null ? 0 : this.getCvePlaza().hashCode());
		result = 37 * result + (getCveSitio() == null ? 0 : this.getCveSitio().hashCode());
		return result;
	}

}
